### ISSUE TITLE
Support syncing tags and notes with DIM

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#299]
Initial idea would be a user clickable "Import from DIM" and "Export to DIM" button to sync tags and notes on items. 

https://docs.google.com/document/d/17Qn2PtA05EuOfb3-9jxZ8KX6MabPs_JJDiLF2N-jQR8/edit#heading=h.tevz3tc84rgk

**Comment by jondthompson** [comment]
I've honestly been thinking about building a "tag center" that revisits the idea of tags and has an API that allows tools such as d2-checklist and DIM to use the tags from my tools (as well as roughly translate them)

I don't currently like the keep/upgrade/infuse/shard schema, and here's why:

At the beginning of the season, I'm interested in upgrading the best weapons I have to the highest level I have, so if I determine something is good or great, I'll mark it upgrade, and not so great stuff at higher levels I'll mark infuse.  If it is the same item, the upgrade cost is cheap, so I go ahead and do it, but if I don't have something to upgrade I'll keep it for cross-item upgrading.  

As my level increases, I then have to clean out the crap that has been building in infuse because I don't need anything lower than what I have already. Eventually I end up only keeping stuff at the soft level cap and higher, and then eventually just the hard cap.

However, once the season turns over that stuff is useless, so I have to clean that stuff out and start the process over again.

So infuse and shard are really the same thing, but the light level tells me whether I should actually keep it or not. Keep and upgrade don't make sense to me because why would you want to keep something you're not going to upgrade?  Maybe in an archival type of sense, but then the term archive makes it more clear why you would want to do this.
---

I'd rather see these tags-
keepPvP - which will upgrade it cheaply whenever possible. It also tells you why you wanted it in the first place.
keepPvE - which will upgrade it cheaply whenever possible. It also tells you why you wanted it in the first place.
keepBoth - which will upgrade it cheaply whenever possible. It also tells you why you wanted it in the first place.
trash - it'll hold on to what makes sense to hold onto, and walk you through sharding anything else. 
archive - for the hoarders that want to keep stuff just 'cuz

--- 

Long term, I _really_ believe Bungie should implement tagging into the API so that there can be some in-game usage, as well as putting the data where it belongs, but that's probably not happening at this point.

**Comment by dcaslin** [comment]
This is finally done!

**Comment by jondthompson** [comment]
Oh? Sweet!  Is there a setup that needs done?

**Comment by dcaslin** [comment]
It should auto prompt you. Details here: https://www.reddit.com/r/destinychecklistnet/comments/mxxm00/d2checklist_introducing_dim_sync_for_d2checklist/
