### ISSUE TITLE
Clan triumphs for Conqueror not displayed properly

### ISSUE THREAD

**Issue by michaelaird** [dcaslin/d2-checklist#378]
I think the triumphs for completing the GM nightfalls during the season of the chosen are actually showing completions from a previous season.

**Comment by dcaslin** [comment]
Sorry took me a while to get to this. It's possible the API has changed since you reported this, but at the moment I see it listing the correct 6 GM's, however it's never showing completions for any of them. I think this is a problem with the underlying API and just filed a bug w/ Bungie about it, thanks! https://github.com/Bungie-net/api/issues/1460

**Comment by SolidKalium** [comment]
Hey, following up from the linked bug report, it occurred to me that I didn't see in the API how gilded triumphs are tied to a season. You may want to follow up next week when Season 14 is released to figure out how to display that.

The only record value on these gilded triumphs I haven't figured out is the featuredPriority. So if the needed info is already in the API, I'd guess it's that value.
